const properties = [
    {
        id: 1,
        title: "Tiara Estate",
        price: 22000000,
        location: "Ibeju Lekki, Lagos",
        type: "Landed Property",
        size: 400,
        sizeUnit: "sqm",
        bedrooms: "N/A",
        status: "Sold Out",
        offer: "",
        description: "A luxurious and spacious landed property located in the fast-developing area of Ibeju Lekki. Perfect for building your dream home or for investment purposes. Comes with excellent amenities and a serene environment.",
        mainImage: "./images/2.jpg",
        gallery: ["./images/11.jpg", "./images/22.jpg", "./images/33.jpg"]
    },
    {
        id: 2,
        title: "Victoria Crest V",
        price: 95000000,
        location: "Orchid, Lekki",
        type: "Duplex",
        size: 600,
        sizeUnit: "sqm",
        bedrooms: 4,
        status: "For Sale",
        offer: "",
        description: "Experience luxury living in this stunning 4-bedroom terrace duplex at Victoria Crest V. Featuring modern architecture, premium finishes, and a host of world-class amenities in a secure and serene estate.",
        mainImage: "./images/3.jpg",
        gallery: ["./images/44.jpg", "./images/55.jpg"]
    },
    {
        id: 3,
        title: "Amen Estate Phase 3",
        price: 30000000,
        location: "Ibeju Lekki, Lagos",
        type: "Landed Property",
        size: 500,
        sizeUnit: "sqm",
        bedrooms: "N/A",
        status: "For Sale",
        offer: "Hot Offer!",
        description: "Amen Estate Phase 3 offers you the opportunity to own a piece of the new Lagos. This estate provides a perfect blend of nature, functionality, and lifestyle. Secure your plot now and be part of this thriving community.",
        mainImage: "./images/4.jpg",
        gallery: ["./images/22.jpg"]
    },
    {
        id: 4,
        title: "Fairmont Green Estate",
        price: 18000000,
        location: "Ibeju Lekki, Lagos",
        type: "Landed Property",
        size: 300,
        sizeUnit: "sqm",
        bedrooms: "N/A",
        status: "For Sale",
        offer: "",
        description: "Fairmont Green Estate is an eco-friendly development that offers a blend of nature and modern living. It is a perfect choice for those who appreciate tranquility and a green environment.",
        mainImage: "./images/5.jpg",
        gallery: ["./images/11.jpg"]
    },
    {
        id: 5,
        title: "Lagoon Front Estate",
        price: 14000000,
        location: "Epe, Lagos",
        type: "Landed Property",
        size: 300,
        sizeUnit: "sqm",
        bedrooms: "N/A",
        status: "Sales Closed",
        offer: "",
        description: "Enjoy the scenic views of the Lagos Lagoon from your own property. The Lagoon Front Estate is a prime location for residential and commercial development, offering a high return on investment.",
        mainImage: "./images/6.jpg",
        gallery: ["./images/33.jpg"]
    },
    {
        id: 6,
        title: "Modern 5-Bed Duplex",
        price: 150000000,
        location: "Ikoyi, Lagos",
        type: "Duplex",
        size: 600,
        sizeUnit: "sqm",
        bedrooms: 5,
        status: "For Sale",
        offer: "New Listing",
        description: "A masterpiece of modern architecture, this 5-bedroom fully detached duplex in Ikoyi offers unparalleled luxury. Features include a private cinema, swimming pool, and state-of-the-art security.",
        mainImage: "./images/7.jpg",
        gallery: ["./images/22.jpg", "./images/44.jpg"]
    }
];
